#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Installation of HAproxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

# makes sure that HAproxy can be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1' /etc/default/haproxy

# configuring HAproxy so that it sends traffic to web-01 and web-02
FRONTEND_CONFIG="frontend web_frontend
	bind *:80
	mode http
	default_backend web_backend"

BACKEND_CONFIG="backend web_backend
	balance roundrobin
	server 463220-web-01 54.237.97.154:80 check
	server 463220-web-02 54.224.31.23:80 check"

echo "$FRONTEND_CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "$BACKEND_CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg

# restart haproxy service
sudo service haproxy restart
