#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
mysqldump -u root --password "$1" --all-databases > backup.sql
tar -czvf "$file_name" backup.sql
