#!/usr/bin/env bash
# fixes nginx to listen to port 80 and kills it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" > /run/nginx.pid
