#!/usr/bin/env bash
# This script displays to infinity and beyond indefinitely and I am invincible!!! when SIGTERM signal
terminate() {
	echo "I am invincible!!!"
	exit 0
}
trap terminate SIGTERM
while true; do
        echo "To infinity and beyond"
        sleep 2
done
