#!/usr/bin/env bash
# This script displays to infinity and beyond indefinitely and I am invincible!!! when SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
        echo "To infinity and beyond"
        sleep 2
done
