#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration
count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 8 ]
	then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	((count++))
done
