#!/usr/bin/env bash
# Bash script that configures a Ubuntu server
sudo sed -i -r -e 's/^127.0.0.1\s+localhost/127.0.0.2 localhost/g' /etc/hosts
echo -e "8.8.8.8\tfacebook.com" | sudo tee -a /etc/hosts
