#!/usr/bin/env bash
# Configures the container so that Nginx is running as nginx user
# must listen to port 8080
pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
